# Generated by Django 4.2.6 on 2023-12-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0013_remove_hiring_sys_db_updated_at_and_more'),
        ('AdminEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_reps_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_msg', models.TextField(blank=True, max_length=300, null=True)),
                ('rep_option', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_req', to='UserFront.hiring_sys_db')),
            ],
        ),
    ]
