# Generated by Django 4.2.6 on 2023-11-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0005_worker_db_dob'),
        ('UserFront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=140, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFront.user_reg_db')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkerEnd.worker_db')),
            ],
        ),
    ]
