# Generated by Django 4.2.6 on 2023-11-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0003_reviewrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
