# Generated by Django 4.2.6 on 2023-11-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0005_worker_db_dob'),
        ('UserFront', '0004_rename_user_id_reviewrating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='UserFront.user_reg_db'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='WorkerEnd.worker_db'),
        ),
    ]
