# Generated by Django 4.2.6 on 2023-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0008_hiring_sys_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring_sys_db',
            name='o_status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
