# Generated by Django 4.2.6 on 2023-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0010_rename_o_date_hiring_sys_db_o_f_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rej_rs',
            name='rad_reason',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
