# Generated by Django 4.2.6 on 2023-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0011_rej_rs_rad_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring_sys_db',
            name='o_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hiring_sys_db',
            name='o_town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
