# Generated by Django 4.2.6 on 2023-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0012_hiring_sys_db_o_district_hiring_sys_db_o_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring_sys_db',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hiring_sys_db',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
