# Generated by Django 4.2.6 on 2023-12-18 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0013_remove_hiring_sys_db_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='message_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_body', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=50)),
                ('roomid', models.CharField(max_length=300)),
            ],
        ),
    ]
