# Generated by Django 4.2.6 on 2023-12-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0014_chatroom_db_message_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatroom_db',
        ),
    ]
