# Generated by Django 4.2.6 on 2023-12-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0006_worker_db_black_points'),
        ('UserFront', '0015_delete_chatroom_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_client', to='UserFront.user_reg_db')),
                ('sk_hv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_skh', to='WorkerEnd.worker_db')),
            ],
        ),
    ]
