# Generated by Django 4.2.6 on 2023-12-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0016_chatroom_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_db',
            name='roomid',
            field=models.IntegerField(),
        ),
    ]
