# Generated by Django 4.2.6 on 2023-12-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserFront', '0017_alter_message_db_roomid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_db',
            old_name='user',
            new_name='sender_user',
        ),
    ]
