# Generated by Django 4.2.6 on 2023-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0002_worker_db_username_alter_worker_db_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_login_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_username', models.CharField(blank=True, max_length=150, null=True)),
                ('work_pass', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker_db',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker_db',
            name='mobile',
        ),
    ]
