# Generated by Django 4.2.6 on 2023-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0003_worker_login_db_remove_worker_db_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_db',
            old_name='skill',
            new_name='skill_1',
        ),
        migrations.AddField(
            model_name='worker_db',
            name='disp_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='district',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='mob_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='mob_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='skill_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='worker_db',
            name='town',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
