# Generated by Django 4.2.6 on 2023-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0004_rename_skill_worker_db_skill_1_worker_db_disp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_db',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
