# Generated by Django 4.2.6 on 2023-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0005_worker_db_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_db',
            name='black_points',
            field=models.IntegerField(default=0),
        ),
    ]
