# Generated by Django 4.2.6 on 2023-12-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0006_worker_db_black_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_db',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
