# Generated by Django 4.2.6 on 2023-12-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerEnd', '0008_remove_worker_db_is_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_db',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
